# Generated by Django 2.2.3 on 2019-07-18 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sellers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.IntegerField()),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('cpf', models.IntegerField()),
                ('comission_plan', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('comission', models.DecimalField(decimal_places=2, max_digits=20)),
                ('sellers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Sellers')),
            ],
        ),
        migrations.CreateModel(
            name='Comission_plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=100)),
                ('lower_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('upper_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('min_value', models.DecimalField(decimal_places=2, max_digits=19)),
                ('sellers', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='selec', to='api.Sellers')),
            ],
        ),
    ]
