# Generated by Django 2.2.3 on 2019-07-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellers',
            name='cpf',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='sellers',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
