# Generated by Django 2.2.3 on 2019-07-11 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellers',
            name='cpf',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sellers',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
